// Bangladesh birds (GBIF 0008757-260921141020460) through the app: timing and results
import { createRequire } from 'module'; const require = createRequire(import.meta.url); const fs = require('fs');
import { chromium } from 'playwright';
const file = process.argv[2] || '/home/claude/gbif2/Bangladesh_birds_unique_sites.csv';
const sizes = process.argv[3] || '10, 25, 50';
const browser = await chromium.launch({ executablePath: process.env.CHROME || '/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell', args: ['--js-flags=--max-old-space-size=4096'] });
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } }); const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('file://' + process.cwd() + '/Gridrich.html'); await page.waitForTimeout(400);
let t = Date.now();
await page.setInputFiles('#boundaryInput', ['' + (process.argv[4] || 'test/bgd_example_divisions.geojson') + '']); await page.waitForTimeout(800);
console.log('boundary:', await page.$eval('#boundaryInfo', e => e.textContent));
t = Date.now();
await page.setInputFiles('#recordsInput', [file]);
await page.waitForFunction(() => /Loaded|Error|see/.test(document.getElementById('recordsStatus').textContent), null, { timeout: 600000 });
console.log('records read in', ((Date.now() - t) / 1000).toFixed(1), 's ->', await page.$eval('#recordsStatus', e => e.textContent), '|', await page.$eval('#recordsInfo', e => e.textContent));
await page.check('#regionsOn').catch(() => {});
await page.fill('#cellSizes', sizes); await page.fill('#minOverlap', process.argv[5] || '0'); await page.check('#rarefyOn'); await page.fill('#rarefyN', '50');
t = Date.now(); await page.click('#runBtn');
await page.waitForFunction(() => /Done|Error/.test(document.getElementById('log').textContent), null, { timeout: 1800000 });
console.log('run in', ((Date.now() - t) / 1000).toFixed(1), 's');
console.log(await page.$eval('#log', e => e.textContent.trim().split('\n').slice(-12).join('\n')));
const got = await page.evaluate(() => ({ ds: S.dataSummary, sum: S.results.map(r => r.summary), reg: S.regions ? S.regions.items.map(r => ({ name: r.name, n_occ: r.n_occ, richness: r.richness, rar: r.richness_rarefied, area: Math.round(r.area_km2), per1000: r.occ_per_1000km2 })) : null, nOut: S.regions && S.regions.nOut }));
console.log('data summary:', JSON.stringify(got.ds));
for (const s of got.sum) console.log(JSON.stringify(s));
console.log('regions:', JSON.stringify(got.reg), 'outside all:', got.nOut);
await page.click('.tabs button[data-tab=charts]'); await page.waitForTimeout(500);
console.log('reading:', (await page.$eval('#reading', e => e.innerText)).slice(0, 1500));
await page.click('.tabs button[data-tab=similarity]'); await page.waitForTimeout(500);
console.log('sim:', await page.$eval('#simTiles', e => e.innerText.replace(/\n/g, ' | ')));
await page.selectOption('#mapVar', 'richness'); await page.selectOption('#basemap', 'both'); await page.waitForTimeout(500);
await page.$eval('#mapwrap', e => e.scrollIntoView()); await page.screenshot({ path: 'test/birds_map.png', clip: { x: 430, y: 0, width: 960, height: 640 } });
t = Date.now(); const dl = page.waitForEvent('download'); await page.click('.tabs button[data-tab=export]'); await page.click('#dlXlsx'); await (await dl).saveAs('test/birds.xlsx');
console.log('xlsx in', ((Date.now() - t) / 1000).toFixed(1), 's, size', fs.statSync('test/birds.xlsx').size);
console.log('errors:', errs);
await browser.close();
